microsoft/vscode-l10n

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/main.ts
l10n-dev/src/test/main.test.ts

based on the language used in our language packs

override a couple languages

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

otherwise it will only replace the first instance

mark regex as global

---

l10n/package-lock.json
l10n/package.json
l10n/src/main.ts
l10n/src/test/main.test.ts

Support URLs directly and turn strings into URLs for readFileSync

Support URLs directly and turn strings into URLs for readFileSync

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

* Fix Windows path handlng fixes https://github.com/microsoft/vscode/issues/161945
* Add a script name instead of relying on name at runtime fixes https://github.com/microsoft/vscode/issues/161946
* Fix escaping ampersands

Multiple fixes

---

.github/workflows/pr-chat.yml

Add pr-chat.yml

---

.gitignore
l10n-dev/.esbuild.config.js
l10n-dev/api-extractor.json
l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts
l10n-dev/src/cli.ts
l10n-dev/src/common.ts
l10n-dev/src/main.ts
l10n-dev/src/test/main.test.ts
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts
l10n/.esbuild.config.js
l10n/api-extractor.json
l10n/package-lock.json
l10n/package.json
l10n/src/main.ts
tsconfig.json

You can look at this by commit:
* Onboard to API extractor for cleaner dts (needed to get l10n-dev working in Core build)
* Use new signal for hashing (needed allow us to replace XLF logic in Core with logic in l10n-dev)
* rev version of the packages
* updates based on API sync

A few improvements

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

I've noticed our localization PRs have been big because keys are jumping around the file. My sorting we ensure a consistant shape.

Sort XLF result for consistent git diffs

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts
l10n-dev/src/cli.ts
l10n-dev/src/common.ts
l10n-dev/src/main.ts
l10n-dev/src/test/main.test.ts

This will pave the way for supporting webviews and notebook renderers

Support TSX files to be scanned

---

l10n-dev/README.md
l10n/README.md

Fixes https://github.com/microsoft/vscode/issues/164561

Update README links so they work on npm website

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/test/main.test.ts
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts
l10n/package-lock.json
l10n/package.json

Sort results for more predictability

---

build/pipeline.yml
l10n/package-lock.json
l10n/package.json

Note: this still keeps the initial approval.

Rev version and also don't require approval at the end

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts

Discovered here https://github.com/microsoft/vscode-emmet-helper/pull/71#issuecomment-1312331156
Fixes https://github.com/microsoft/vscode-l10n/issues/51

Handle variables declared elsewhere

---

l10n-dev/README.md

fix command in README

---

README.md

Fixes https://github.com/microsoft/vscode-l10n/issues/61

Update README to call out version of VS Code required

---

l10n/README.md

fix import

---

l10n/src/main.ts
l10n/src/test/main.test.ts

Extensions that are a part of a language pack have a different schema than extensions that bundle their strings with the extension.
This change detects the difference and initializes the bundle accordingly. This is a temporary solution for #84 until a larger change can be made. Either:
* Reworking the structure of language packs to separate bundle and package entrypoints
* Having the client cache the language pack extensions in a way such that they align with extensions that ship their own strings
* Changing the schema of the bundles in extensions that ship their own strings to align with language pack extensions
There's a lot to research there, so in the meantime, this fix unblocks us.
Also, this has better error handling for the uri case.
Fixes #84

Detect built-in (aka language pack) extensions

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts

fixes https://github.com/microsoft/vscode-l10n/issues/106
I have a lengthier fix in mind, but we'll start here for the release.

force path handling to be posix so glob works

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts
l10n-dev/src/logger.ts
l10n-dev/src/main.ts

Now you can use `-d` for debug logging which is super chatty... and `-v` for verbose which is slightly more detailed than normal.
ref https://github.com/microsoft/vscode-l10n/issues/28

Add debug and verbose logging

---

l10n-dev/src/logger.ts

fix: tslint error before publish

---

l10n/src/main.ts

Skip regex.replace() cost when there's nothing to replace

---

.github/workflows/ci.yml
build/pipeline.yml
l10n/package-lock.json
l10n/package.json
l10n/src/main.ts
l10n/src/node/reader.ts

Now that the extension host is Node 18

drop dependency on request-light, use native fetch

---

l10n-dev/src/ast/queries.ts

fix: capture template substitution in template strings

---

l10n-dev/package.json
l10n/package-lock.json
l10n/package.json

specify preset so that tests work in their respective folders

---

l10n/api-extractor.json

Fix API Extractor path

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts
l10n-dev/src/main.ts
l10n-dev/src/translators/azure.ts
l10n-dev/src/translators/pseudo.ts

This feature allows you to use [Azure AI Translator](https://azure.microsoft.com/en-us/products/ai-services/ai-translator) to translate extension strings.
1. Spin up an Azure Translator instance
2. Set these env vars: `AZURE_TRANSLATOR_KEY` and `AZURE_TRANSLATOR_REGION`
3. `vscode-l10n-dev generate-azure ./foo.l10n.json`
The default will translate for all the supported langauges of VS Code
Perhaps we can consider hosting an instance for customers.

Experimental Azure Translate feature

---

l10n-dev/README.md
l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts
l10n-dev/src/translators/azure.ts

Handle character limit better and include missed languages

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/translators/azure.ts

Fixes https://github.com/microsoft/vscode-l10n/issues/159

Fix logic around batching requests

---

.github/workflows/ci.yml
build/pipeline.yml
l10n-dev/package-lock.json
l10n-dev/package.json

Addresses https://github.com/tree-sitter/tree-sitter/issues/2338

chore: bump tree-sitter-cli@0.22.2

---

.github/workflows/ci.yml
build/pipeline.yml
l10n-dev/.esbuild.config.mjs
l10n-dev/package-lock.json
l10n-dev/package.json
l10n/.esbuild.config.js
l10n/package-lock.json

One thing this fixes is that l10n-dev will compile on Windows on ARM.

Fix build and bump a few packages

---

l10n-dev/.esbuild.config.mjs
l10n/.esbuild.config.js

> sus... I was thinking there was some floating task happening ... like a watch task that was being stood up.
You're absolutely right!
On a more serious note, Copilot Chat with GPT-5 helped me find an API to call.
Confirmation build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=353637&view=results

chore: dispose esbuild contexts
