l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts

This will make it easier to use in vscode-engineering so that existing extensions don't get random empty files in their package

skip file writing if nothing interesting will be spit out

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

if we leave the double quote in there, it messes up the XML so we need to escape it

escape double quotes if in id

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts
l10n-dev/src/main.ts
l10n-dev/src/test/main.test.ts

adds a command that can generate a pseudo language bundle. Skips over `command:` and `$(icon)` syntaxes.

Generate Pseudo files utility

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/test/main.test.ts
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

We do this to avoid the 512 limit that the localization team has.
Luckily the id is useless to us as we can re-compute it from the source

Use hash for id

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/test/main.test.ts
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

For package.nls.json files, the user defines the id so we special case that one in the XLF generation and parsing to keep the id.

Have package ids be honored

---

l10n-dev/src/main.ts
l10n-dev/src/test/main.test.ts
l10n/package-lock.json
l10n/package.json
l10n/src/main.ts
l10n/src/test/main.test.ts

* l10n-dev pseudo should not localize `{this}`
* l10n should use the same format function as Core

Support object args to align with API

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts
l10n-dev/src/cli.ts
l10n-dev/src/test/main.test.ts

emmet has an emmet helper npm library that runs in the extension host... when building vscode, that helper library is JS so this change will also pick up calls to `vscode.l10n.t` in that library as well.

Support JS files

---

l10n/.esbuild.config.js
l10n/package-lock.json
l10n/package.json
l10n/src/browser/reader.ts
l10n/src/main.ts
l10n/src/node/reader.ts
l10n/src/test/main.test.ts

So that webworkers can be localized.
Kinda a big PR but in short it's:
* abstracting away any OS operations so that now there's a node & browser separation of file reading logic
* have 3 different `config` overloads (contents - best, fsPath - node only, Uri - async)
* esbuild updates to support main and browser

Support running in browsers

---

l10n/.esbuild.config.js
l10n/package-lock.json
l10n/package.json
l10n/src/test/smoke.esm.html
l10n/src/test/smoke.iife.html

Before, I don't think you could actually use this package because it never had a global name in the `iife` case...
So this gives a global name to the `iife` and also adds an `esm` target for anyone using modules.
I added a couple of html files that act as a manual smoke tests for these two cases too.

Properly support browsers

---

l10n-dev/src/cli.ts

Since most users will manually interact with the exported file.
Fixes https://github.com/microsoft/vscode-l10n/issues/54

Export with spaces

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

Part of:
https://github.com/microsoft/vscode/issues/165735
This fixes the problem where the translated string wasn't being read from the bundle correctly, because this bad regex was including newlines in the key that was generated when it shouldn't have.

Parse XLF notes correctly

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/queries.ts
l10n-dev/src/ast/test/analyzer.test.ts
l10n-dev/src/xlf/test/xlf.test.ts

Before, we were querying for only `string_fragments` but those fragments are not actually the full string. If your string has a `\n` in it, then your `string` has 2 `string_fragments` in it.
So this PR selects the `string` instead of the `string_fragment`... but that has a downside that it includes the quotes... so we need to exclude the quotes.
Fixes #63

Handle newlines correctly

---

l10n-dev/src/xlf/test/xlf.test.ts
l10n-dev/src/xlf/xlf.ts

Newlines being treated as newlines seemed to mess up the XML parser.
This change now turns them into their charcodes `10` and `13` so that
they can be parsed correctly.
With that said, one bug I noticed in the XML parser is that if a value
only contains newline characters, then it treats it as an empty string.
I will open an issue about this in the xml2js repo.
Fixes #63

Handle newlines in XLFs better

---

build/pipeline.yml

Since that is the only platform that can _build_ the WASM grammars.
On Windows & macOS, it will run fine but it can't be built on these platforms without Docker.

Only run l10n-dev on Linux

---

l10n-dev/.esbuild.config.mjs
l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/ast/analyzer.ts

Because we have to load the WASM files as runtime, the CLI was failing to load them because when the CLI is bundled the paths are different.
This moves the WASM files in to the ast directory and then ensures they are copied into the dist.

Allow WASM files to be loaded in the CLI

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts

In the VS Code repo, I was seeing an issue where the parser and grammar were being loaded multiple times
And in some cases, because of my if not checking if the grammar was defined, it would totally fail.
This change ensures that both grammar and parser will be defined.

Better handling of grammar and parser

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts

tree-sitter gives the text as is... so if a message says `'foo\'bar'` you're gonna get `'foo\'bar'` exactly.
This needs to be handled so that the escaped single quote becomes only a single quote in the end.
Fixes #73

Fix escaped quotes

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/test/analyzer.test.ts
l10n-dev/src/cli.ts
l10n-dev/src/test/cli.test.ts
l10n-dev/src/test/testcases/big.txt

Use an indirect eval to ensure escape characters are handled correctly.
Since the client will be "running" the string inside of `l10n.t()` this is the best way to ensure alignment.
Note that our query currently doesn't pick up references like this:
* `l10n.t("foo" + "bar")`
* or:
```
l10n.t(`backticks`)
```
So we don't have to worry about eval failing.
Fixes #73 
Fixes #76 
Fixes #66

Handle escape characters better and honor `l10n` in package.json

---

l10n-dev/src/cli.ts
l10n-dev/src/test/cli.test.ts
l10n-dev/src/test/testcases/big.txt
l10n-dev/src/test/testcases/test.xml
l10n-dev/src/test/testcases/testBundle.json
l10n-dev/src/xlf/xlf.ts
l10n/src/main.ts

This adds a few CLI tests and in doing so, I realized a few things:
1. @vscode/l10n wasn't joining with `''` so it was adding commas which wasn't aligned with the client. Now they are.
2. xlf parsing wasn't replacing all newlines so I added the `g`
also
Fixes #75

Misc fixes

---

l10n/package.json

Refs https://github.com/microsoft/vscode-js-debug/issues/1624
I noticed that issue was being called by new syntax being used in the bootloader that Node 12 didn't understand. But localizations shouldn't be in the bootloader at all, and with this change, it enables @vscode/l10n to be tree shaken out.
Separate issue is why our test suites that nominally run Node 8 didn't pick up on this earlier...

fix: mark @vscode/l10n as side-effect-free

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/queries.ts
l10n-dev/src/ast/test/analyzer.test.ts
l10n-dev/src/ast/test/unescapeString.test.ts
l10n-dev/src/ast/unescapeString.ts
l10n/src/main.ts
l10n/src/test/main.test.ts

This adds a new format of localization that can be used like
```js
l10n.lit`Hello ${name}!`
```
This approach makes it easier to write translations without an
error-prone process of manual replacements (https://github.com/microsoft/vscode-js-debug/pull/1693/files)
Template literals do not allow for comments; for that I suggest users
go back to `l10n.t`. I thought about some overload syntax that would be
a higher order function like
```js
l10n.lit({ comment: 'here' })`Hello ${name}!`
```
...which could be a nice future addition?
This is not supported in the vscode ext host API yet... but it could be :)

feat: add `l10n.lit` for tagged template literal translations (it's lit)

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts
l10n-dev/src/test/cli.test.ts

The glob library is very powerful. This change refactors things so that there are no more nested globs. Additionally, I got rid of the nasty `toPosixPath` function.
Oh, and added a cli test for pseudo generation.

Use glob library more

---

l10n-dev/package-lock.json
l10n-dev/package.json
l10n-dev/src/cli.ts

Passing outDir to command always outputs warning that it doesn't match packageJSON.l10n value.

---

l10n/src/main.ts

fix: #117 Provide a usage example for t(options) signature

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/queries.ts
l10n-dev/src/ast/test/analyzer.test.ts

Fixes https://github.com/microsoft/vscode-l10n/issues/78

fix: allow template strings in `l10n.t` calls

---

l10n-dev/src/ast/analyzer.ts
l10n-dev/src/ast/queries.ts
l10n-dev/src/ast/test/analyzer.test.ts

* We were using the Template Raw Value instead of the Template Value (Template Value normalizes new lines to just LF)
* Template string comments were not getting picked up
* Bunch of tests

Fix a couple issues with template strings

---

build/pipeline.yml

Verification build https://dev.azure.com/monacotools/Monaco/_build/results?buildId=259791&view=results

chore: skip APIScan for l10n-dev
